# Generated by Django 4.1 on 2022-10-19 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "ticket_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[("AD", "ADULT"), ("CH", "CHILD"), ("SR", "SENIOR")],
                        max_length=2,
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.seatinshowing",
                    ),
                ),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.showing"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.promo",
                    ),
                ),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.showing"
                    ),
                ),
                ("tickets", models.ManyToManyField(to="checkout.ticket")),
            ],
        ),
    ]
