# Generated by Django 4.1 on 2022-10-19 00:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='code',
            field=models.CharField(default='9Q07A2', max_length=6),
        ),
        migrations.AlterField(
            model_name='promo',
            name='exp_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 17, 20, 11, 3, 155052)),
        ),
    ]
