# Generated by Django 4.1.3 on 2022-11-23 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="8XPNHF", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 12, 23, 15, 25, 59, 111794)
            ),
        ),
    ]
