# Generated by Django 4.1 on 2022-09-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="movie", options={"verbose_name_plural": "Movies"}
        ),
        migrations.AddField(
            model_name="movie",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="movie", name="release_date", field=models.DateField(null=True)
        ),
        migrations.AddField(
            model_name="movie",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="rating", field=models.CharField(max_length=200)
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="tag_line",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="movie", name="title", field=models.CharField(max_length=200)
        ),
    ]
