# Generated by Django 4.1 on 2022-09-28 19:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0003_promo")]

    operations = [
        migrations.AddField(
            model_name="promo",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
        ),
        migrations.AddField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 28, 19, 13, 0, 471394)
            ),
        ),
        migrations.CreateModel(
            name="Showing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showtime", models.DateTimeField()),
                ("room", models.CharField(max_length=200)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.movie"
                    ),
                ),
            ],
        ),
    ]
