# Generated by Django 4.1 on 2022-09-28 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_promo_discount_promo_exp_date_showing")]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="producer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="pic",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 28, 16, 42, 23, 965281)
            ),
        ),
    ]
