# Generated by Django 4.1 on 2022-10-18 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0006_alter_promo_code_alter_promo_exp_date")]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="QJ9QA0", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 17, 0, 59, 27, 419111)
            ),
        ),
    ]
