# Generated by Django 4.1 on 2022-10-05 05:58

import datetime
from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_rename_tag_line_movie_tag_alter_genre_title_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="cast",
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="HGR58Z", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 4, 1, 58, 21, 570425)
            ),
        ),
    ]
