# Generated by Django 4.1 on 2022-10-15 17:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0007_alter_promo_code_alter_promo_exp_date")]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.mpaa"
            ),
        ),
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="TNMENO", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 14, 13, 42, 17, 314468)
            ),
        ),
    ]
