# Generated by Django 4.1 on 2022-10-16 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_alter_movie_rating_alter_promo_code_and_more")]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="BNQVHS", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 14, 23, 57, 45, 62837)
            ),
        ),
    ]
