# Generated by Django 4.1 on 2022-10-05 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_alter_promo_code_alter_promo_exp_date")]

    operations = [
        migrations.CreateModel(
            name="MPAA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.CharField(max_length=200, unique=True)),
            ],
            options={"verbose_name_plural": "MPAA Rating"},
        ),
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="6GA6X6", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 4, 1, 25, 2, 611976)
            ),
        ),
    ]
