# Generated by Django 4.1 on 2022-10-16 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0009_alter_promo_code_alter_promo_exp_date")]

    operations = [
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="G71Q6H", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 15, 0, 59, 24, 338917)
            ),
        ),
    ]
