# Generated by Django 4.1 on 2022-10-05 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0009_remove_movie_cast_alter_promo_code_and_more")]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actor_ids",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="promo",
            name="code",
            field=models.CharField(default="46F5CA", max_length=6),
        ),
        migrations.AlterField(
            model_name="promo",
            name="exp_date",
            field=models.DateField(
                default=datetime.datetime(2022, 11, 4, 2, 14, 58, 672883)
            ),
        ),
    ]
