# Generated by Django 4.1 on 2022-10-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_mpaa_alter_promo_code_alter_promo_exp_date"),
        ("core", "0010_movie_actor_ids_alter_promo_code_and_more"),
    ]

    operations = []
