# Generated by Django 4.1.3 on 2022-11-23 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("checkout", "0001_initial"), ("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.address",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bookings",
            field=models.ManyToManyField(to="checkout.booking"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="selected_card",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="current_selected_card",
                to="accounts.paymentcard",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.customersatus",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="usercards",
            field=models.ManyToManyField(
                blank=True, null=True, to="accounts.paymentcard"
            ),
        ),
    ]
