# Generated by Django 4.1 on 2022-10-13 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address1",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Address line 1",
                    ),
                ),
                (
                    "address2",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Postal Code"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="City"
                    ),
                ),
                (
                    "sate",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="State"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Country"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="receive_promos",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.address",
            ),
        ),
    ]
