# Generated by Django 4.1 on 2022-10-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_address_customuser_bookings_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(blank=True, upload_to="profiles/"),
        )
    ]
