# Generated by Django 4.1 on 2022-10-13 06:58

import creditcards.models
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_customuser_receive_promos_customuser_address")
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cc_number",
                    creditcards.models.CardNumberField(
                        max_length=25, verbose_name="card number"
                    ),
                ),
                (
                    "cc_expiry",
                    creditcards.models.CardExpiryField(verbose_name="expiration date"),
                ),
                (
                    "cc_code",
                    creditcards.models.SecurityCodeField(
                        max_length=4, verbose_name="security code"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="address", name="country"),
        migrations.AlterField(
            model_name="address",
            name="sate",
            field=localflavor.us.models.USStateField(
                blank=True, max_length=2, null=True, verbose_name="State"
            ),
        ),
    ]
