# Generated by Django 4.1 on 2022-10-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0003_paymentcard_remove_address_country_and_more")]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="paymentcards",
            field=models.ManyToManyField(to="accounts.paymentcard"),
        )
    ]
