# Generated by Django 4.1 on 2022-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0004_customuser_paymentcards")]

    operations = [
        migrations.AddField(
            model_name="paymentcard",
            name="name",
            field=models.CharField(blank=True, max_length=120, null=True),
        )
    ]
