# Generated by Django 4.1 on 2022-10-13 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0005_paymentcard_name")]

    operations = [
        migrations.CreateModel(
            name="CustomerSatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=100, unique=True)),
            ],
        )
    ]
