# Generated by Django 4.1 on 2022-10-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_alter_customuser_address")]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profiles/default_profile.jpg",
                null=True,
                upload_to="profiles/",
            ),
        )
    ]
