# Generated by Django 4.1 on 2022-10-13 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("accounts", "0006_customersatus")]

    operations = [
        migrations.AlterModelOptions(
            name="address", options={"verbose_name_plural": "Address"}
        ),
        migrations.AlterModelOptions(
            name="customersatus", options={"verbose_name_plural": "Customer Status"}
        ),
        migrations.AddField(
            model_name="customuser",
            name="status",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.customersatus",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="paymentcards",
            field=models.ManyToManyField(null=True, to="accounts.paymentcard"),
        ),
    ]
