# Generated by Django 4.1 on 2022-10-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_address_options_alter_customersatus_options_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.address",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="paymentcards",
            field=models.ManyToManyField(
                blank=True, null=True, to="accounts.paymentcard"
            ),
        ),
    ]
