# Generated by Django 4.1 on 2022-10-15 03:14

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [("accounts", "0008_alter_customuser_address_and_more")]

    operations = [
        migrations.AlterField(
            model_name="paymentcard",
            name="cc_number",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        )
    ]
