# Generated by Django 4.1 on 2022-10-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0008_alter_customuser_profile_pic")]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        )
    ]
