# Generated by Django 4.1 on 2022-10-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0009_alter_paymentcard_cc_number")]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="paymentcards",
            field=models.ManyToManyField(blank=True, to="accounts.paymentcard"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="receive_promos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
