# Generated by Django 4.1 on 2022-10-16 03:57

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0010_alter_customuser_paymentcards_and_more")]

    operations = [
        migrations.RemoveField(model_name="address", name="sate"),
        migrations.AddField(
            model_name="address",
            name="state",
            field=localflavor.us.models.USStateField(
                default="GA", max_length=2, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address1",
            field=models.CharField(
                default="", max_length=1024, verbose_name="Address line 1"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="", max_length=1024, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(
                default="", max_length=12, verbose_name="Postal Code"
            ),
        ),
    ]
