# Generated by Django 4.1 on 2022-10-16 04:59

import creditcards.models
from django.db import migrations, models
import encrypted_model_fields.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0011_remove_address_sate_address_state_and_more")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="state",
            field=localflavor.us.models.USStateField(
                default="", max_length=2, verbose_name="State"
            ),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="cc_code",
            field=creditcards.models.SecurityCodeField(
                max_length=4, verbose_name="Security Code"
            ),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="cc_expiry",
            field=creditcards.models.CardExpiryField(verbose_name="Expiration Date"),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="cc_number",
            field=encrypted_model_fields.fields.EncryptedCharField(
                verbose_name="Card Number"
            ),
        ),
        migrations.AlterField(
            model_name="paymentcard",
            name="name",
            field=models.CharField(
                default="", max_length=120, verbose_name="Name on Card"
            ),
        ),
    ]
